#config.yaml

#absolute or relative
cram_dir: input_data/

out_dir: results/

#absolute (ends in '/')
manta_dir: tools/manta-1.6.0.centos6_x86_64/
melt_dir: tools/MELTv2.2.2/

#list format example
sample_name: ['sample_1', 'sample_2']
